### ISSUE TITLE
Can´t sing in

### ISSUE THREAD

**Issue by LoboIngeniero** [AngelShtarbev/Angular2-Firebase-Auction-App#1]
Hello, great work!!

but i can´t sing in. Says "Error: Your API key is invalid, please check you have copied it correctly."

Why ???

Thanks a lot!

**Comment by AngelShtarbev** [comment]
Hey there,

The problem is probably with the firebase api key.

Follow this tutorial to solve it:

https://coursetro.com/posts/code/32/Create-a-Full-Angular-Authentication-System-with-Firebase

Note that in order to use the payment methods you have to sign up for both
Stripe & Paypal testing accounts / api keys.

The below tutorial can be helpfull for simple payment integration with
Stripe:

http://blog.mgechev.com/2016/07/05/using-stripe-payment-with-angular-2
